#!/usr/bin/env expect
#==============================================================================
#
#          FILE:  ssh
#         USAGE:  ./ssh
#   DESCRIPTION:  Executes an scp connection to a pre-defined server
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#==============================================================================
if { [ info exists env(ENABLE_LOG_USER) ] } {
    if { [ string match -nocase $env(ENABLE_LOG_USER) "true" ] == 1 } {
        log_user 1;
    } else {
        log_user 0;
    }
} else {
    log_user 0;
}

if { [ info exists env(DEBUG_TCL) ] } {
    if { [ string match -nocase $env(DEBUG_TCL) "true" ] == 1 } {
        exp_internal 1;
    }
}
log_user 1
exp_internal 1
log_file -a $env(HOME)/.log/ssh.log;

## set up some class info
global env;
global _CNAME;
global _METHOD_NAME;
global _LINE_TERMINATOR;

set _CNAME "ssh";
set _METHOD_NAME "ssh";
set _LINE_TERMINATOR "\r\n";
set timeout 10;

if { [info exists env(THREAD_TIMEOUT)] } {
    set timeout $env(THREAD_TIMEOUT);
}

source [ file join [ file dirname [ info script ] ] getAuthValue.tcl ];
source [ file join [ file dirname [ info script ] ] changeAccountPassword.tcl ];

proc usage {} {
    global _METHOD_NAME;

    puts stderr "$_METHOD_NAME Perform an automated SSH-based task without user interaction.";
    puts stderr "Usage: $_METHOD_NAME \[ host \] \[ user \] \[ command \] ( timeout )";
    puts stderr "\thost                The target hostname to connect to. The host must be either an IP address or resolvable hostname.";
    puts stderr "\tusername            The user to connect to the remote system as.";
    puts stderr "\tcommand             The command to execute on the remote system. If an interactive shell is required, specify 'shell' here.";
    puts stderr "\ttimeout             A timeout value for the script to wait if it hangs. If not specified, a value of 10 seconds is used.";

    exit 1;
}

## make sure we have all our arguments
if { [ expr { $argc < 3 } ] } {
    usage;
} else {
    ## set runtime information
    set _TARGET_SYSTEM [ lindex $argv 0 ];
    set _USER_LOGINID [ lindex $argv 1 ];
    set _EXEC_CMD [ lindex $argv 2 ];
    set _AUTH_DATA [ getAuthValue $_TARGET_SYSTEM $_USER_LOGINID ];

    switch [ llength $_AUTH_DATA ] {
        1 {
            set _USER_PASSWD $_AUTH_DATA;
        }
        2 {
            set _USER_KEY [ lindex $_AUTH_DATA 0 ];
            set _USER_PASSWD [ lindex $_AUTH_DATA 1 ];
        }
    }

    if { [ expr { $argc eq 5 } ] } {
        set timeout [ lindex $argv 4 ];
    }
}

switch [ info exists _USER_LOGINID ] {
    0 {
        if { [ string match -nocase $_EXEC_CMD "shell" ] } {
            eval spawn ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no -qaCktl $_USER_LOGINID $_TARGET_SYSTEM;
        } else {
            eval spawn ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no -qaCktl $_USER_LOGINID $_TARGET_SYSTEM \"$_EXEC_CMD\";
        }
    }
    1 {
        switch [ info exists _USER_KEY ] {
            0 {
                if { [ string match -nocase $_EXEC_CMD "shell" ] } {
                    eval spawn ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no -qaCktl $_USER_LOGINID $_TARGET_SYSTEM;
                } else {
                    eval spawn ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no -qaCktl $_USER_LOGINID $_TARGET_SYSTEM \"$_EXEC_CMD\";
                }
            }
            1 {
                if { [ string match -nocase $_USER_KEY "default" ] } {
                    if { [ string match -nocase $_EXEC_CMD "shell" ] } {
                        eval spawn ssh -qaCktl $_USER_LOGINID $_TARGET_SYSTEM;
                    } else {
                        eval spawn ssh -qaCktl $_USER_LOGINID $_TARGET_SYSTEM \"$_EXEC_CMD\";
                    }
                } else {
                    if { [ string match -nocase $_EXEC_CMD "shell" ] } {
                        eval spawn ssh -qaCktl $_USER_LOGINID -i $_USER_KEY $_TARGET_SYSTEM;
                    } else {
                        eval spawn ssh -qaCktl $_USER_LOGINID -i $_USER_KEY $_TARGET_SYSTEM \"$_EXEC_CMD\";
                    }
                }
            }
        }
    }
}

set i 0;

expect {
    "*(yes/no)? " {
        exp_send "yes\r";
        exp_continue;
    }
    "*id_?sa*" {
        if { [ info exists _USER_PASSWD ] } {
            exp_send "$_USER_PASSWD";
        }

        exp_send "\r";
        exp_continue;
    }
    "*Changing password for *$_USER_LOGINID*" {
        ## set up password change here
        if { [info exists env(NEW_PASSWORD_FILE)] } {
            set _ENCRYPTED $env(ENCR_TYPE);
            set _CHANGE_DATA [ getAuthValue $_TARGET_SYSTEM $_USER_LOGINID $env(NEW_PASSWORD_FILE) ];
        }

        if { [ string compare $_EXEC_CMD "passwd" ] == 0 } {
            set _RETURN_VALUE [ changeAccountPassword "account" "false" "$_USER_LOGINID" "$_USER_PASSWD" "$_CHANGE_DATA" ];
        } else {
            set _RETURN_VALUE [ changeAccountPassword "account" "true" "$_USER_LOGINID" "$_USER_PASSWD" "$_CHANGE_DATA" ];
        }

        switch $_RETURN_VALUE {
            1 - 2 - 3 {
                puts stderr "Unable to change password for provided user account $_USER_LOGINID on host $_TARGET_SYSTEM";

                exit 0;
            }
            default {
                puts "Password successfully changed for user $_USER_LOGINID to $_RETURN_VALUE on host $_TARGET_SYSTEM";
            }
        }
    }
    "*?assword*" {
        if { [ expr { $i == 1 } ] } {
            puts stderr "An invalid password was provided for user account $_USER_LOGINID on host $_TARGET_SYSTEM";

            exit 1;
        }

        set i [ expr { $i + 1 } ];

        exp_send "$_USER_PASSWD\r";
        exp_continue;
    }
    $_LINE_TERMINATOR {
        expect {
            "*Changing password for $_USER_LOGINID*" {
                ## set up password change here
                exp_send "$_USER_PASSWD\r";

                set _RETURN_VALUE [ changeAccountPassword "account" "true" "$_USER_LOGINID" "$_USER_PASSWD" ];

                switch $_RETURN_VALUE {
                    1 - 2 - 3 {
                        puts stderr "Unable to change password for provided user account $_USER_LOGINID on host $_TARGET_SYSTEM";

                        exit 0;
                    }
                    default {
                        puts "Password successfully changed for user $_USER_LOGINID to $_RETURN_VALUE on host $_TARGET_SYSTEM";
                    }
                }
            }
            "*?assword*" {
                if { [ expr { $i == 1 } ] } {
                    puts stderr "An invalid password was provided for user account $_USER_LOGINID on host $_TARGET_SYSTEM";

                    exit 1;
                }

                set i [ expr { $i + 1 } ];

                exp_send "$_USER_PASSWD\r";
                exp_continue;
            }
            $_LINE_TERMINATOR {
                if { [ string compare $_EXEC_CMD "shell" ] == 0 } {
                    exp_send "\r";
                    interact;
                } else {
                    if { [ string compare $_EXEC_CMD "passwd" ] == 0 } {
                        set _RETURN_VALUE [ changeAccountPassword "account" "false" "$_USER_LOGINID" "$_USER_PASSWD" ];

                        switch $_RETURN_VALUE {
                            1 - 2 - 3 {
                                puts stderr "Unable to change password for provided user account $_USER_LOGINID on host $_TARGET_SYSTEM";

                                exit 0;
                            }
                            default {
                                puts "Password successfully changed for user $_USER_LOGINID to $_RETURN_VALUE on host $_TARGET_SYSTEM";
                            }
                        }
                    }

                    append output $expect_out(buffer);
                    exp_continue;
                }
            }
            eof {
                append output $expect_out(buffer);
            }
        }
    }
    eof {
        append output $expect_out(buffer);
    }
}

if { [ info exists output ] eq 1 } {
    regsub -all -line {^[ \r\t]+|[ \r\t]+$} $output "" _RETURN_DATA;
    set _PRINT_DATA [ string trimright $_RETURN_DATA ];

    if { [ string compare -nocase $_PRINT_DATA "" ] != 0 } {
        if { [ string is integer $_PRINT_DATA ] } {
            exit $_PRINT_DATA;
        } else {
            puts $_PRINT_DATA;

            exit 0;
        }
    } else {
        exit 0;
    }
}
